### ISSUE TITLE
make.bat missing in the repo

### ISSUE THREAD

**Issue by clebig** [Eun/icmpmon#1]
Hi Tobias,

In the build instructions, you say to use "make.bat". I don't find it in your repo. 
I've tried directly invoking "go build" on icmpmon directory but it fails.

Would it be possible to push the make.bat to the repo ?

Thank you.
Clément

**Comment by Eun** [comment]
Hello,
I guess you can just take the main.bat file from an older commit: https://github.com/Eun/icmpmon/blob/675e0719faba3218096ccf1fdb6d1df3579219c8/make.bat

**Comment by clebig** [comment]
Yes, it made it. Thank you.

I built it with musl (Running Alpine). I have a panic when I start it. I will open a new issue for this specific problem.

**Comment by clebig** [comment]
The panic came from an IPv6 host declared in the config when I was running without ipv6 enabled on the system.
